# First do some basic training with same params for every tool of top-10
train1:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_0_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
train2:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_1_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
train3:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_2_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
train4:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_3_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
train5:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_4_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
train6:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_5_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
train7:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_6_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
train8:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_7_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
train9:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_8_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
train10:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_9_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"

# Try some other params for tool 0
train11:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_0_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "poisson"
train12:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_0_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
    bootstrap: False
train13:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_0_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 500
    random_state: 0
    criterion: "absolute_error"
train14:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_0_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
    warm_start: True
train15:
  dataset_path: "../processed_data/sampled_data/20000_samples_of_tool_number_0_seed_100.txt"
  is_mixed_data: False
  seed: 0
  model_params:
    n_estimators: 200
    random_state: 0
    criterion: "absolute_error"
    oob_score: True